# Generated by Django 4.0.5 on 2022-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_Birth', models.DateField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('N/A', 'N/A')], default='Male', max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='single', max_length=20)),
                ('emergency_contact', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('other_medications_reason', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('assignedDoctorId', models.PositiveIntegerField(default=0)),
                ('admitDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
