# Generated by Django 4.0.5 on 2022-07-05 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_alter_patient_admitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 6, 50, 15, 558436, tzinfo=utc)),
        ),
    ]
