# Generated by Django 4.0.5 on 2022-07-05 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_alter_patient_admitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 7, 15, 24, 467652, tzinfo=utc)),
        ),
    ]
