# Generated by Django 4.0.5 on 2022-07-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_patient_admitdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 7, 12, 24, 48, 885753)),
        ),
    ]
