# Generated by Django 4.0.5 on 2022-07-04 12:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0007_alter_doctor_department_alter_doctor_marital_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDischargeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientName', models.CharField(max_length=20)),
                ('date_service_end', models.DateField(null=True)),
                ('room_type', models.CharField(max_length=30, null=True)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('admitDate', models.DateTimeField()),
                ('releaseDate', models.DateField(default=datetime.datetime(2022, 7, 4, 17, 34, 40, 728635))),
                ('daySpent', models.PositiveIntegerField()),
                ('roomCharge', models.PositiveIntegerField()),
                ('medicineCost', models.PositiveIntegerField()),
                ('doctorFee', models.PositiveIntegerField()),
                ('OtherCharge', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('attending_physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
    ]
