# Generated by Django 4.0.5 on 2022-07-05 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdischarge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdischargedetails',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 15, 39, 17, 211820)),
        ),
    ]
