# Generated by Django 4.0.5 on 2022-07-05 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdischarge', '0002_patientdischargedetails_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 5, 22, 23, 7, 242024)),
        ),
    ]
