# Generated by Django 4.0.5 on 2022-07-07 06:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdischarge', '0003_alter_patientdischargedetails_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 7, 12, 24, 48, 888562)),
        ),
    ]
