# Generated by Django 4.0.5 on 2022-07-08 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientdischarge', '0004_alter_patientdischargedetails_releasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='releaseDate',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 14, 9, 35, 432941)),
        ),
    ]
