# Generated by Django 4.0.5 on 2022-06-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=70)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], default='Single', max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender'), ('N/A', 'N/A')], default='Male', max_length=20)),
                ('department', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons'), ('Pediatricians', 'Pediatricians'), ('Ophthalmologists', 'Ophthalmologists'), ('Endocrinologists', 'Endocrinologists'), ('Gastroenterologists', 'Gastroenterologists'), ('Nephrologists', 'Nephrologists'), ('Urologists', 'Urologists'), ('Pulmonologists', 'Pulmonologists'), ('Otolaryngologists', 'Otolaryngologists'), ('Neurologists', 'Neurologists'), ('Psychiatrists', 'Psychiatrists'), ('Oncologists', 'Oncologists'), ('Radiologists', 'Radiologists'), ('Rheumatologists', 'Rheumatologists')], default='Cardiologist', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
